---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apples.demo.example.com
spec:
  group: demo.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                color:
                  type: string
                taste:
                  type: string
                quantity:
                  type: integer
  scope: Namespaced
  names:
    plural: apples
    singular: apple
    kind: Apple
    shortNames:
      - apl

