apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  namespace: default
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","echo 'hello' > /cache/data.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

