apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","echo 'node storage' > /data/log.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: host-storage
  volumes:
  - name: host-storage
    hostPath:
      path: /tmp/k8s-hostpath
      type: DirectoryOrCreate

